name: DockerImage

on:
  push:
    branches:
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - 
        uses: aws-actions/setup-sam@v1
        with:
          version: 1.37.0
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile.finn
          context: .
          push: true
          tags: maltanar/finn:dev_latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
